# fly.toml app configuration file generated for yt-coverhunter on 2025-04-02T06:04:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yt-coverhunter'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0


[[vm]]
  size = "shared-cpu-4x"
  memory = '4096mb'

[mounts]
source="yt_cover_data"
destination="/data"
