WAV_FOLDER: /tmp/youtube_cover_detector_api_wav
MODEL_FOLDER: /code/pretrain_model
COVERHUNTER_FOLDER: /code/
THRESHOLD: 0.3
YT_DLP_USE_COOKIES: False
SCORES_CSV_FILE: /data/compared_videos.csv
VECTORS_CSV_FILE: /data/vectors.csv
PROCESS_ONLY_FIRST_N_SECONDS: -1  # This means processing entire audio files
STATIC_FOLDER: /code/static
REQUEST_TIMEOUT: 55  # Server-side timeout matching client MAX_TOTAL_TIME
CLEANUP_ON_TIMEOUT: true  # Ensure resources are cleaned up on timeout
MAX_CONCURRENT_REQUESTS: 3  # Limit concurrent processing
SCORES_CSV_FILE_BACKUP: /data/compared_videos.csv.backup
VECTORS_CSV_FILE_BACKUP: /data/vectors.csv.backup
BACKUP_INTERVAL: 3600  # Backup interval in seconds
